### ISSUE TITLE
Why ROS 1 over ROS 2?

### ISSUE THREAD

**Issue by PositiveBeat** [Red-Rabbit-Robotics/rx1#1]
Hi! 

Very exciting project.

How come the choice to use ROS 1, and not ROS 2?

**Comment by zlingkang** [comment]
I have used ROS1 for years and I don't have much experience with ROS2. ROS 1 just fast for me to prototype. I think after this going forward I am more likely to develop something more generic without dependency on ROS, like a pure Python API or something like that.

**Comment by PositiveBeat** [comment]
Aaah, that makes a lot of sense. Thank you for all this cool work 😄

**Comment by PositiveBeat** [comment]
Aaah, that makes a lot of sense. Thank you for all this cool work 😄
