### ISSUE TITLE
Compile error on rx1_motor

### ISSUE THREAD

**Issue by cholet852** [Red-Rabbit-Robotics/rx1#2]
Hi, I have a compilation problem with rx1_motor.

Here is the error:

[ 82%] Linking CXX executable /home/exotrapp/catkin_ws/devel/lib/rx1_motor/rx1_motor_node
/usr/bin/ld: /home/exotrapp/catkin_ws/devel/lib/librx1_motor.so: undefined reference to `rx1_motor::Rx1Motor::TORSO_ACC_'
/usr/bin/ld: /home/exotrapp/catkin_ws/devel/lib/librx1_motor.so: undefined reference to `rx1_motor::Rx1Motor::ARM_ACC_'
/usr/bin/ld: /home/exotrapp/catkin_ws/devel/lib/librx1_motor.so: undefined reference to `rx1_motor::Rx1Motor::TORSO_SPEED_'
/usr/bin/ld: /home/exotrapp/catkin_ws/devel/lib/librx1_motor.so: undefined reference to `rx1_motor::Rx1Motor::ARM_SPEED_'
/usr/bin/ld: /home/exotrapp/catkin_ws/devel/lib/librx1_motor.so: undefined reference to `rx1_motor::Rx1Motor::HEAD_ACC_'
/usr/bin/ld: /home/exotrapp/catkin_ws/devel/lib/librx1_motor.so: undefined reference to `rx1_motor::Rx1Motor::HEAD_SPEED_'
collect2: error: ld returned 1 exit status
make[2]: *** [rx1/rx1_motor/CMakeFiles/rx1_motor_node.dir/build.make:120: /home/exotrapp/catkin_ws/devel/lib/rx1_motor/rx1_motor_node] Error 1
make[1]: *** [CMakeFiles/Makefile2:2180: rx1/rx1_motor/CMakeFiles/rx1_motor_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 88%] Linking CXX shared library /home/exotrapp/catkin_ws/devel/lib/librx1_ik.so
[ 88%] Built target rx1_ik
make: *** [Makefile:141: all] Error 2
Invoking "make -j4 -l4" failed

**Comment by zlingkang** [comment]
Thanks for reporting! It seems that some compiler doesn't like the static constexpr in the header file. There are two ways to solve it, you can either add `add_compile_options(-std=c++17)` to your CMakeLists.txt to he rx1_motor (I have just pushed this change, you just need to pull the latest again).

Alternatively, if you don't want to use c++17, you could also change the static constexpr values in the rx1 motor header file to pure const, like `const double TORSO_ACC_=1.5`

**Comment by cholet852** [comment]
great, I just recompiled and it works perfectly. Thank you so much
